spring:
  application:
    name: module1

  boot:
    admin:
      client:
        url: http://localhost:8080

  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
